name: demo
description: "demo app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  freezed_annotation: ^3.0.0
  fluttertoast: ^8.2.14
  loader_overlay: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/
